#!/bin/bash
__PWD=`pwd`

if [ -e ./customrc ]; then
    source ./customrc
fi

export BR2_EXTERNAL=${__PWD}/openpower
export BR2_DL_DIR=${__PWD}/dl

shopt -s expand_aliases
alias op-build="make --directory=${__PWD}/buildroot O=${__PWD}/output "
