//parameters([
//    ])
properties([buildDiscarder(logRotator(daysToKeepStr: '30'))])
node ('podman_test'){
timestamps {
ansiColor("xterm") {
    stage('op-build compile') {
                
        cleanWs()

        sh '''#!/bin/bash -e
        git clone --recurse-submodules --single-branch --branch master-p10 git@github.com:open-power/op-build.git $WORKSPACE/op-build
        cd $WORKSPACE/op-build
        if [[ "$CHANGE_ID" != "" ]]; then   
            git fetch origin pull/$CHANGE_ID/head
            git checkout -b $CHANGE_ID FETCH_HEAD 
        fi

        ci/ibm/podman_jenkins.sh

        '''
        def artifacts = ['op-build/ci/ibm', 'op-build/timings.txt', 'op-build/upload.log']
        archiveArtifacts artifacts: artifacts.join(', '), allowEmptyArchive: true

        cleanWs()
    }
}
}
}